### ISSUE TITLE
Protocol 4 arguments issue

### ISSUE THREAD

**Issue by ai** [logux/django#42]
We used the new RC1 version in our production and got an error:

```
2020-08-04 02:20:17,350 - logux.dispatchers - INFO - registering action `message_thread/add`
logux actions added
2020-08-04 02:20:17,350 - logux.dispatchers - INFO - registering subscription for `^message_thread`
channels registered
2020-08-04 02:20:18,034 - logux.dispatchers - INFO - registering action `message_thread/add`
logux actions added
2020-08-04 02:20:18,035 - logux.dispatchers - INFO - registering subscription for `^message_thread`
channels registered
INFO 2020-08-04 02:20:18,044 Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 04, 2020 - 02:20:18
Django version 2.2.13, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
ERROR 2020-08-04 02:20:21,661 Internal Server Error: /logux/
Traceback (most recent call last):
  File "/home/ai/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ai/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ai/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/ai/.local/lib/python3.8/site-packages/logux/views.py", line 137, in dispatch
    status, commands_results = LoguxRequest(request).apply_commands()
  File "/home/ai/.local/lib/python3.8/site-packages/logux/views.py", line 124, in apply_commands
    return 200, list(filter(None, chain.from_iterable([cmd.apply() for cmd in self.commands])))
  File "/home/ai/.local/lib/python3.8/site-packages/logux/views.py", line 124, in <listcomp>
    return 200, list(filter(None, chain.from_iterable([cmd.apply() for cmd in self.commands])))
  File "/home/ai/.local/lib/python3.8/site-packages/logux/core.py", line 566, in apply
    'channels': self.resend(self._action, self._meta, self._headers)
TypeError: resend() takes 3 positional arguments but 4 were given
ERROR 2020-08-04 02:20:21,662 "POST /logux/ HTTP/1.1" 500 97532
```

**Comment by ai** [comment]
Back-end code:

```python
from typing import Optional, Dict

from cities.models import MessageThread, Message
from cities.models.user import User

from logux.core import ActionCommand, Meta, Action
from logux.dispatchers import logux


class SubscribeAction(ActionCommand):
    action_type = "message_thread/subscribe"


class UnsubscribeAction(ActionCommand):
    action_type = "message_thread/unsubscribe"


class AddMessageAction(ActionCommand):
    action_type = "message_thread/add"

    def resend(self, action: Action, meta: Optional[Meta]) -> Dict:
        # return {"channels": [f"message_thread/{action['messageThreadId']}"]}
        return {"channels": [f"message_thread"]}

    def access(self, action: Action, meta: Optional[Meta]) -> bool:
        return True

    def process(self, action: Action, meta: Optional[Meta]):
        print("add message process")
        client = User.objects.get(id=int(meta.user_id))
        message_thread = MessageThread.objects.get(id=action["messageThreadId"])
        Message.objects.create(
            author=client, message_thread=message_thread, body=action["body"]
        )


logux.actions.register(AddMessageAction)
print("logux actions added")
```

Server code:

```js
    server.log.add({
      type: "message_thread/add",
      messageThreadId: 1,
      body: "test message"
    });
```

**Comment by egregors** [comment]
@ai You have used an outdated `resend` signature (`headers: Dict` arg was added for proto4 support) from outdated docs. You should override the `resend` method from `ActionCommand` class: https://github.com/logux/django/blob/master/logux/core.py#L498 with the same signature. 

Please, check out the examples in https://github.com/logux/django/blob/master/tests/test_app/logux_actions.py 

```python
class RenameUserAction(ActionCommand):
    action_type = 'users/name'

    def resend(self, action: Action, meta: Optional[Meta], headers: Dict) -> List[str]:
        return [f"users/{action['payload']['userId']}"]

    [...]
```

**Comment by ai** [comment]
Is it mandatory to write `headers: Dict` even if you do not use it? It is a very rare case when a developer will need `headers`.

Can we move, in the future, it to `self.headers` since `headers` move the context of the connection, rather than exact action?

**Comment by egregors** [comment]
> Is it mandatory to write headers: Dict

No, you could hide it behind `**kwargs`, like `def resend(self, action: Action, **kwargs) -> List[str]`.
You could, but you shouldn't. 

> Can we move, in the future, it to self.headers since headers move the context of the connection, rather than exact action?

Yes, we can, but for me, it looks a bit awkward
